server:
  grpc:
    addr: ${GRPC_ADDR:0.0.0.0:9000}
    timeout: 1s
auth:
  access:
    private: ${ACCESS_PRIVATE}
    expiry: ${ACCESS_EXPIRY}
    public: ${ACCESS_PUBLIC}
  refresh:
    private: ${REFRESH_PRIVATE}
    expiry: ${REFRESH_PRIVATE}
    public: ${REFRESH_PRIVATE}
providers:
  redirect_url: ${REDIRECT_URL}
  google:
    client_id: ${GOOGLE_CLIENT_ID}
    client_secret: ${GOOGLE_CLIENT_SECRET}
  facebook:
    client_id: ${FB_CLIENT_ID}
    client_secret: ${FB_CLIENT_SECRET}
data:
  database:
    source: ${DB_SOURCE}
  redis:
    addr: ${REDIS_SOURCE}
    read_timeout: 0.2s
    write_timeout: 0.2s
services:
  user:
    endpoint: ${USER_ENDPOINT}
